# Generated by Django 4.2.4 on 2023-09-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=16)),
                ('birthdate', models.DateField()),
                ('gender', models.BooleanField()),
                ('password', models.CharField(max_length=20)),
                ('bookinfo', models.TextField(null=True)),
                ('boardinfo', models.TextField(null=True)),
            ],
        ),
    ]
