# Generated by Django 4.2.4 on 2023-09-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
