# Generated by Django 4.2.4 on 2023-09-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
