# Generated by Django 4.2.4 on 2023-09-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=8)),
                ('cno', models.CharField(max_length=8)),
                ('allerinfo', models.TextField(null=True)),
                ('cdate', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('serialno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cno', models.CharField(max_length=8)),
                ('cdate', models.DateField()),
                ('bno', models.ForeignKey(db_column='bno', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.board')),
            ],
        ),
    ]
