# Generated by Django 4.2.4 on 2023-10-14 05:21

import board.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=8, null=True)),
                ('cno', models.CharField(max_length=8, null=True)),
                ('allerinfo', models.TextField()),
                ('cdate', models.DateField()),
                ('ingredient', models.JSONField()),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('types', models.TextField(null=True)),
                ('meterial', models.TextField(null=True)),
            ],
            options={
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='BSimilarity',
            fields=[
                ('bno', models.IntegerField(primary_key=True, serialize=False)),
                ('simlist', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
            options={
                'db_table': 'bsimilarity',
            },
        ),
        migrations.CreateModel(
            name='MeterialCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterials', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'meterial_categories',
            },
        ),
        migrations.CreateModel(
            name='TypeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('serialno', models.AutoField(primary_key=True, serialize=False)),
                ('cno', models.CharField(max_length=8)),
                ('cdate', models.DateField(blank=True, null=True)),
                ('udate', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('bno', models.ForeignKey(db_column='bno', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.board')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=board.models.get_image_filename)),
                ('bno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
            options={
                'db_table': 'board_images',
            },
        ),
    ]
