# Generated by Django 4.2.4 on 2023-09-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cno',
            field=models.ForeignKey(db_column='cno', on_delete=django.db.models.deletion.CASCADE, related_name='id', to='signapp.customer'),
        ),
    ]
