# Generated by Django 4.2.4 on 2023-09-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0001_initial'),
        ('board', '0002_alter_comment_cno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cno',
            field=models.ForeignKey(db_column='cno', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='signapp.customer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bno',
            field=models.ForeignKey(db_column='bno', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.board'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cno',
            field=models.ForeignKey(db_column='cno', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='signapp.customer'),
        ),
    ]
