# Generated by Django 4.1.7 on 2023-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_recipe_alter_board_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ingredient',
            field=models.CharField(default='NULL', max_length=500),
            preserve_default=False,
        ),
    ]
