# Generated by Django 4.1.7 on 2023-09-15 17:51

import board.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='ingredient',
            field=board.models.JSONListField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=board.models.JSONListField(),
        ),
    ]
