# Generated by Django 4.2.4 on 2023-09-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_cno_alter_comment_bno_alter_comment_cno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cno',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bno',
            field=models.ForeignKey(db_column='bno', on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.board'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cno',
            field=models.CharField(max_length=8),
        ),
    ]
