# Generated by Django 4.2.4 on 2023-09-21 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_alter_allergy_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('prdNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('simlist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None)),
            ],
            options={
                'db_table': 'similarity',
            },
        ),
    ]
